### ISSUE TITLE
What is the supported Node version?

### ISSUE THREAD

**Issue by mdinuth** [davedoesdev/node-jsjws#10]
I was trying to use this library for PS256 and the code that I have written works perfectly in latest Node version v8.9. I'm planning to integrate this code into an AWS Lamba function which only supports Node v6.10. 

In Node v6.10, I'm getting the following error and unable to verify PS256 signatures.

> dlopen(/Projects/Code/JWTValidation/node_modules/jsjws/build/Release/turbokey.node, 1): Symbol not found: _napi_create_error
  Referenced from: /Projects/Code/JWTValidation/node_modules/jsjws/build/Release/turbokey.node
  Expected in: flat namespace
 in /Projects/Code/JWTValidation/node_modules/jsjws/build/Release/turbokey.node
Falling back to slow path (keypair)
{ verification: false, error: 'Key must be a buffer' }
cmlddezoysa:JWTValidation ddezoysa$ node index.js 
dlopen(/Projects/Code/JWTValidation/node_modules/jsjws/build/Release/turbokey.node, 1): Symbol not found: _napi_create_error
  Referenced from: /Projects/Code/JWTValidation/node_modules/jsjws/build/Release/turbokey.node
  Expected in: flat namespace
 in /Projects/Code/JWTValidation/node_modules/jsjws/build/Release/turbokey.node
Falling back to slow path (keypair)
/Projects/Code/JWTValidation/src/jwt/jwt-ps256.js:23
        throw err;
        ^
> TypeError: Key must be a buffer
>     at TypeError (native)
>     at Verify.verify (crypto.js:311:23)
>     at verify (/Projects/Code/JWTValidation/node_modules/jsjws/lib/jsjws.js:17712:24)
>     at Function.KJUR.jws.JWS.verify (/Projects/Code/JWTValidation/node_modules/jsjws/lib/jsjws.js:4296:13)
>     at KJUR.jws.JWS.verifyJWSByKey (/Projects/Code/JWTValidation/node_modules/jsjws/lib/jsjws.js:17276:26)
>     at Object.exports.verifyJWT (/Projects/Code/JWTValidation/src/jwt/jwt-ps256.js:20:26)
>     at Object.exports.processJWT (/Projects/Code/JWTValidation/src/jwt/jwt-handler.js:62:30)
>     at Object.<anonymous> (/Projects/Code/JWTValidation/index.js:35:25)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)

Appreciate if you can provide a solution.

**Comment by davedoesdev** [comment]
Unfortunately only 8 onwards is supported:

```json
  "engines": {
    "node": ">=8.7.0"
  }
```

because support for RSASSA-PSS padding was only added from Node 8.

**Comment by davedoesdev** [comment]
By the way, on Node 8, if you add `--napi-modules` then you should get fast path key generation.

**Comment by davedoesdev** [comment]
@mdinuth there is a forum thread here about AWS support for Node 8:

https://forums.aws.amazon.com/thread.jspa?threadID=266753
