### ISSUE TITLE
not compatible with node.js 0.12 or io.js

### ISSUE THREAD

**Issue by adrai** [davedoesdev/node-jsjws#4]
npm installation fails :-(

**Comment by davedoesdev** [comment]
Thanks for the heads up. Looks like a bunch of work to do in ursa plus hopefully simple stuff in the wrapper. I'll check whether ursa has a maintainer now...

**Comment by davedoesdev** [comment]
Looks like they're working on it: https://github.com/NodePrime/ursa/issues/73
What I need to do is get the changes in my fork into ursa.

**Comment by adrai** [comment]
Thanks to you :-)

**Comment by davedoesdev** [comment]
Needs https://github.com/NodePrime/ursa/issues/73 to land first.

**Comment by adrai** [comment]
Seams to be really near: https://github.com/NodePrime/ursa/pull/76

**Comment by davedoesdev** [comment]
Yep, once that's in I'll take a look

**Comment by adrai** [comment]
Any news?

**Comment by davedoesdev** [comment]
Not had time yet, sorry.

**Comment by davedoesdev** [comment]
Probably be a couple of weeks I'm afraid

**Comment by davedoesdev** [comment]
ursa work done in https://github.com/quartzjer/ursa/pull/80
Once that's on npm I'll set about fixing node-jsjws.

**Comment by adrai** [comment]
nice

**Comment by adrai** [comment]
It's on npm ;-)

**Comment by davedoesdev** [comment]
@adrai  I've published a new version which passes tests on 0.12. Please give it a try and let me know how it goes.

**Comment by adrai** [comment]
ok unit tests are green... :+1:  now testing some e2e tests...

**Comment by adrai** [comment]
seams to be ok...
