### ISSUE TITLE
Verification bypass vulnerability

### ISSUE THREAD

**Issue by evilpacket** [davedoesdev/node-jsjws#5]
Can you confirm if node-jsjws is vulnerable or not to the issue described in the below post? We would like to properly communicate to the community which modules are vulnerable or not via the node security project. Will try and help verify but short on time atm.

https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by adrai** [comment]
https://github.com/kjur/jsjws/issues/25

**Comment by davedoesdev** [comment]
I'm really grateful to @timmclean in giving me a heads up a few weeks ago.
Patches started here: https://github.com/davedoesdev/node-jsjws/commit/b1ae24fde59d702200d847adaeb213dcf91498ab
Please follow the commit history and let me know what you think.

**Comment by davedoesdev** [comment]
Tests are here:

https://github.com/davedoesdev/node-jsjws/blob/master/test/alg_none_verification_spec.js
https://github.com/davedoesdev/node-jsjws/blob/master/test/allowed_algs_spec.js

**Comment by davedoesdev** [comment]
Oh and here:

https://github.com/davedoesdev/node-jsjws/blob/master/test/pem_as_hmac_key_spec.js

**Comment by davedoesdev** [comment]
Btw I don't know if it's useful but the pre-patched implementation documented the behaviour thus:

> Its signature must verify using the public key or its algorithm must be none.

(https://github.com/davedoesdev/node-jsjws/tree/a9e9a22d0af1113d760d34c7a36a218059cb43e7)

**Comment by adrai** [comment]
Everything done right? -Close?

**Comment by davedoesdev** [comment]
Quick summary:

- 1.x.x behaviour was to allow verification bypass (i.e. even if you passed in a key, verification would bypass if the token's alg was `none`).
- This behaviour was documented but I realised this wasn't good enough when Tim contacted me.
- 2.x.x changes the API so you have to pass `none` in as an allowed algorithm which means you have to make a deliberate choice now.

**Comment by davedoesdev** [comment]
@evilpacket I'm guessing advisories will appear here: https://nodesecurity.io/advisories ?
When are you planning to put something up is this area?

**Comment by davedoesdev** [comment]
@evilpacket OK with you to close this issue now?

**Comment by davedoesdev** [comment]
OK I think I left this open long enough.
