### ISSUE TITLE
node 4 compatibility: update ursa

### ISSUE THREAD

**Issue by adrai** [davedoesdev/node-jsjws#6]
as soon as https://github.com/quartzjer/ursa/issues/102 is released update ursa dependency and publish a new release

**Comment by davedoesdev** [comment]
yep - just testing on another project first

**Comment by davedoesdev** [comment]
Having problems with `ursa` on Travis: https://travis-ci.org/davedoesdev/pub-keystore/builds/83774148
`npm install ursa` works fine for me locally.

**Comment by adrai** [comment]
Perhaps that travis file is missing something... try to compare with: https://github.com/quartzjer/ursa/blob/master/.travis.yml

**Comment by adrai** [comment]
@quartzjer can you help?

Perhaps ursa now only works with node 4 but not with 0.12 anymore?

**Comment by adrai** [comment]
fyi: https://travis-ci.org/davedoesdev/node-jsjws/builds/83825821

**Comment by davedoesdev** [comment]
How strange. I'll look into this, may be a day or two.

**Comment by adrai** [comment]
https://github.com/quartzjer/ursa/issues/110

**Comment by adrai** [comment]
ursa v0.9.1 works great ;-)

**Comment by adrai** [comment]
It's green again ;-) https://travis-ci.org/davedoesdev/node-jsjws/builds/84573777

Thanks again for your help! Great job!

**Comment by davedoesdev** [comment]
Published version 2.1.0.
@adrai thanks for your PR and bringing this to my attention, appreciate it.
